require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ViroSample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])








  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'


  target 'ViroSampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ViroSample-tvOS' do
  # Pods for ViroSample-tvOS

  target 'ViroSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
